[build]
  command = "yarn install --frozen-lockfile && yarn build"
  functions = "netlify/functions"
  publish = "packages/web/.next"
  targetPort = 3003
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "yarn workspace @metalmaster/web dev"
  targetPort = 3000
  functions = "netlify/functions"
