[build]
  command = "yarn install --frozen-lockfile && yarn build"
  publish = "packages/web/.next"
  targetPort = 3003
[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
